#!/bin/bash
apt-get install python-apt python-dev python-lxml python3-pip python3 python3-lxml python3-dev ipython ipython3 -y
pip3 install --upgrade pip
pip3 install requests==2.17.1
pip3 install adblockparser 
pip3 install asn1crypto 
pip3 install attrs 
pip3 install Automat 
pip3 install autopep8 
pip3 install beautifulsoup4 
pip3 install bs4 
pip3 install certifi 
pip3 install cffi 
pip3 install chardet 
pip3 install colorama 
pip3 install configparser 
pip3 install constantly 
pip3 install cryptography 
pip3 install cssselect 
pip3 install decorator 
pip3 install flake8 
pip3 install html5lib 
pip3 install idna 
pip3 install importmagic 
pip3 install incremental 
pip3 install ipython 
pip3 install jedi 
pip3 install jieba 
pip3 install lxml 
pip3 install mccabe 
pip3 install mysqlclient 
pip3 install parsel 
pip3 install parso 
pip3 install pyasn1 
pip3 install pyasn1-modules 
pip3 install pycodestyle 
pip3 install pycparser 
pip3 install pycrypto 
pip3 install pycurl 
pip3 install PyDispatcher 
pip3 install pyflakes 
pip3 install pyOpenSSL 
pip3 install pypinyin 
pip3 install PyVirtualDisplay 
pip3 install queuelib  
pip3 install rope 
pip3 install rope-py3k 
pip3 install selenium 
pip3 install service-identity 
pip3 install setuptools 
pip3 install simplegeneric 
pip3 install six 
pip3 install SQLAlchemy 
pip3 install ssh-import-id 
pip3 install Twisted 
pip3 install urllib3 
pip3 install virtualenv 
pip3 install w3lib 
pip3 install wheel 
pip3 install yapf 
pip3 install zope.interface
pip3 install schedule 
pip3 install scrapy 
  
