#!/bin/bash
apt-get install python-dev python-lxml python3-pip python3 python3-lxml python3-dev ipython ipython3 -y
pip3 install --upgrade pip
pip3 install adblockparser \
     asn1crypto \
     attrs \
     Automat \
     autopep8 \
     beautifulsoup4 \
     bs4 \
     certifi \
     cffi \
     chardet \
     colorama \
     configparser \
     constantly \
     cryptography \
     cssselect \
     decorator \
     flake8 \
     html5lib \
     idna \
     importmagic \
     incremental \
     ipython \
     jedi \
     jieba \
     language-selector \
     lxml \
     mccabe \
     mysqlclient \
     parsel \
     parso \
     pip \
     pyasn1 \
     pyasn1-modules \
     pycodestyle \
     pycparser \
     pycrypto \
     pycurl \
     PyDispatcher \
     pyflakes \
     pygobject \
     pyOpenSSL \
     pypinyin \
     python-apt \
     python-debian \
     python-systemd \
     PyVirtualDisplay \
     queuelib \
     re2 \
     requests \
     rope \
     rope-py3k \
     schedule \
     Scrapy \
     scrapy-splash \
     selenium \
     service-identity \
     setuptools \
     simplegeneric \
     six \
     SQLAlchemy \
     ssh-import-id \
     Twisted \
     ufw \
     unattended-upgrades \
     urllib3 \
     virtualenv \
     w3lib \
     wheel \
     yapf \
     zope.interface
